name: check-grammer
on:
  push:
    branches:
      - master
jobs:
  write-good:
    name: write-good
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: npm install -g write-good
      - run: write-good resume.tex
  proselint:
    name: proselint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
      - uses: BSFishy/pip-action@v1
        with:
          packages: |
            proselint
      - run: proselint resume.tex
